version: '3.8'

services:
  # Service untuk aplikasi Go
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=production
      - PORT=8080
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=db_go_book_prod
      - CLOUDINARY_CLOUD_NAME=dmep42hxi
      - CLOUDINARY_API_KEY=898589439876684
      - CLOUDINARY_API_SECRET=Xj0CiiQwCgsuIyEhv3ap56aOKLE
      - DATABASE_URL=postgres://postgres:password@db:5432/db_go_book_prod?sslmode=disable
    depends_on:
      - db
    volumes:
      - .:/app
    entrypoint: ["/bin/sh", "-c", "chmod +x /app/entrypoint.sh && /app/entrypoint.sh & tail -f /dev/null"]

  # Service untuk PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: db_go_book_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
